# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15ce5b089d25a65df327c13febdccc123b6dbb904cf7105d12812814f7aaa2f29cd5122276a5357f143634bbd802e988c65e11f6affeda70defa6ae601737b9c

test:
  secret_key_base: 6986ebdd5c499f869bd449ef4fd9e8deb246edcba9df9ea6e151b124e2d41e56ce1f0fecb46aea8e0ced48720119e5eaf7222b902dd3ea56dcc686f89d95594c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
